---
authentication:
  keycloak:
<<<<<<< HEAD
    # TODO: not my favorite way to set any URL
    realmUrl: 'https://keycloak-{{ rhsso_project_name }}.apps.{{ subdomain }}/auth/realms/openshift'
    secret: mattermost
=======
    realmUrl: 'https://keycloak-rhsso.apps.sparta.spo.io/auth/realms/openshift'
    secret: 1f6d2d53-6c46-46e9-860c-4ed0c80b703b
>>>>>>> initial mattermost work
