---

plugin: aws_ec2

strict_permissions:  no

regions:
  - us-east-1
  - us-east-2
  - us-west-1

keyed_groups:
  - prefix: openshift_role
    key: tags.OpenShiftRole
  - prefix: openshift_cluster
    key: tags.OpenShiftClusterNameVerbose

groups:
  openshift_nodes:
    tags.OpenShiftRole in ['master', 'worker']
  openshift_bastion:
    tags.OpenShiftBastion == 'true'
