---
- name: "Get Che {{ user.username }} token"
  uri:
    url: "{{ keycloak_url }}/auth/realms/codeready/protocol/openid-connect/token"
    validate_certs: false
    method: POST
    body:
      username: "{{ user.username }}"
      password: "{{ user.password }}"
      grant_type: "password"
      client_id: "codeready-public"
    body_format: form-urlencoded
    status_code: 200
  register: user_token

- name: Create workspace for {{ user.username }} from devfile
  uri:
    url: 'https://{{ codeready_route|json_query("resources[0].spec.host") }}/api/workspace/devfile?start-after-create=true'
    validate_certs: false
    method: POST
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ user_token.json.access_token }}"
    body: "{{ lookup('template', './templates/devfile.json.j2') }}"
    body_format: json
    status_code: 201,409
  register: workspace_def