---
- name: "Get Che {{ user.username }} token"
  uri:
    url: "{{ keycloak_url }}/auth/realms/codeready/protocol/openid-connect/token"
    method: POST
    body:
      username: "{{ user.username }}"
      password: "{{ user.password }}"
      grant_type: "password"
      client_id: "codeready-public"
    body_format: form-urlencoded
    status_code: 200
  register: user_token

- name: Get workspace for {{ user.username }}
  uri:
    url: 'https://{{ codeready_route|json_query("resources[0].spec.host") }}/api/workspace'
    validate_certs: false
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ user_token.json.access_token }}"
    status_code: 200
  register: workspace_def

- name: Verify and start workspace for {{ user.username }} again if stopped
  when: workspace_def.json[0].status == "STOPPED"
  uri:
    url: 'https://{{ codeready_route|json_query("resources[0].spec.host") }}/api/workspace/{{ workspace_def.json[0].id }}/runtime'
    validate_certs: false
    method: POST
    headers:
      Accept: application/json
      Authorization: "Bearer {{ user_token.json.access_token }}"
    status_code: 200