---
ocs_node_query: 'resources[*]|[?contains(@.metadata.annotations."machine.openshift.io/machine", `ocs-worker`)]'
nodes_ready_query: '[].status.conditions[]|[?@.type == `Ready`].status'
ocs_storage_class_query: 'resources[*]|[?@.status.phase == `Ready`].status.storageClassesCreated'
