---
# TODO:
#  - Che/CRW (in catalog)
#  - Gut Jenkins and replace entirely with Tekton
#  - Pipeline rework to match operated services
#  - Service Mesh integration
- import_tasks: user_projects.yml
# - import_tasks: jenkins_operator.yml
# Temporarily disabled as resource requirements are likely too high to justify at this scale
# - import_tasks: ocs.yml
- import_tasks: quay.yml
- import_tasks: gogs.yml
- import_tasks: nexus.yml
- import_tasks: sonarqube.yml
