---
# TODO:
#  - GOGS (https://github.com/wkulhanek/gogs-operator)
#  - Nexus (in catalog)
#  - SonarQube (https://github.com/wkulhanek/sonarqube-operator)
#  - Che/CRW (in catalog)
#  - Pipeline rework to match operated services

- import_tasks: user_projects.yml
- import_tasks: jenkins_operator.yml
# Temporarily disabled as resource requirements are likely too high to justify at this scale
# - import_tasks: ocs.yml
- import_tasks: quay.yml
