---
- name: Generate projects per-user
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "project.yml.j2")|from_yaml }}'

- include_role:
    name: ocs
  when: deploy_ocs|default(true)
- include_role:
    name: quay
  when: deploy_quay|default(true)
- include_role:
    name: service_mesh
  when: deploy_service_mesh|default(true)
- include_role:
    name: gitea
  when: deploy_gitea|default(true)
- include_role:
    name: sonarqube
  when: deploy_sonarqube|default(true)
- include_role:
    name: nexus
  when: deploy_nexus|default(true)
- include_role:
    name: 3scale
  when: deploy_3scale|default(true)
- include_role:
    name: tekton
  when:
    - deploy_pipeline|default(true)
    - pipeline_style|default('tekton') == 'tekton'
- include_role:
    name: jenkins
  when:
    - deploy_pipeline|default(true)
    - pipeline_style|default('tekton') == 'jenkins'
