---
- name: Generate projects per-user
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "project.yml.j2")|from_yaml }}'

- include_role:
    name: quay
  when: deploy_quay|default(true)
- include_role:
    name: service_mesh
  when: deploy_service_mesh|default(true)
- include_role:
    name: gogs
  when: deploy_gogs|default(true)
- include_role:
    name: sonarqube
  when: deploy_sonarqube|default(true)
- include_role:
    name: nexus
  when: deploy_nexus|default(true)
- include_role:
    name: ocs
  when: deploy_3scale|default(true)
