---
- name: Subscribe to Quay Enterprise
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "quay.yml.j2")|from_yaml }}'

- name: Deploy Quay Enterprise via CR
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: redhatcop.redhat.io/v1alpha1
      kind: QuayEcosystem
      metadata:
        name: quayecosystem
        namespace: quay-enterprise
      spec:
        quay:
          imagePullSecretName: redhat-pull-secret
          registryStorage:
            persistentVolumeSize: 10Gi
            persistentVolumeAccessModes:
              - ReadWriteOnce
          database:
            volumeSize: 10Gi
        clair:
          enabled: true
          imagePullSecretName: redhat-pull-secret
  register: quay_deployment
  until: not quay_deployment.failed
  retries: 5
  delay: 10
