---
- name: Generate projects per-user
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "project.yml.j2")|from_yaml }}'

# Since the default (and only supported SDN plugin in 4.2) is OpenShiftSDN
# (which isn't multi-tenant), I'm not going to translate Siamak's "adm
# pod-network join-projects" command. This may need to change later, and we
# should potentially look at "unsupported" SDN plugins to validate some
# potential customer configurations for realism.
