---
- name: Create secrets for every user account in Quay
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "quay_secrets.yml.j2")|from_yaml }}'
  register: quay_secrets
  when: deploy_quay|default(true)

# k8s_json_patch nor normal k8s modules are working here... oc CLI is
- name: Attach new secrets to pipeline service accounts
  shell: |
    export KUBECONFIG='{{ kubeconfig }}'
    oc='{{ tmp_dir }}/oc'
    admin_user='{{ workshop_admin.username }}'
    admin_password='{{ workshop_admin.password }}'
    if [ $($oc whoami) != "$admin_user" ]; then
        $oc login --insecure-skip-tls-verify=true -u "$admin_user" -p "$admin_password" || exit 1
    fi
    user={{ item[0] }}
    project={{ item[1] }}
    $oc patch sa/pipeline -n $user-$project --type=json -p='[
      {"op":"add",
       "path":"/secrets/-",
       "value":{"name":"'"$user-$project"'-quay-reg"}}]' || exit 2
  when:
    - quay_secrets is defined
    - quay_secrets.changed|bool
    - quay_secrets.result|json_query('results[*]|[?@.result.metadata.namespace == `' + item[0] + '-' + item[1] + '`].changed')|first|bool
  with_nested:
    - '{{ workshop_users|json_query("[].username") }}'
    - '{{ projects|json_query("[].name") }}'

- name: Define necessary tasks
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "task_" + task + ".yml.j2")|from_yaml }}'
  loop:
    - mvn_build
  loop_control:
    loop_var: task
