---
- name: Create secrets for every user account in Quay
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "quay_secrets.yml.j2") }}'
  when: deploy_quay|default(true)

- name: Add EAP ImageStreams to every project
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ item[0] }}-{{ item[1] }}'
    definition: '{{ lookup("url", eap_imagestream_source) }}'
  with_nested:
    - '{{ for username in workshop_users|json_query("[].username") }}'
    - '{{ for project in projects|json_query("[].name") }}'

- name: Define necessary tasks
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "task_" + task + ".yml.j2") }}'
  loop:
    - mvn_build
  loop_control:
    loop_var: task
