apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: maven-build-pipeline
  generateName: maven-build-pipeline-
  namespace: user1-cicd
spec:
  pipelineRef:
    name: maven-build-pipeline
  resources:
    - name: app-git
      resourceRef:
        name: source
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: local-maven-repo
      persistentVolumeClaim:
        claimName: maven-local-repo-pvc
