kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-settings-pvc
  namespace: user1-cicd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10m
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
