---
- name: Ensure namespace exists
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ gitea_project_name }}'
        annotations:
          openshift.io/display-name: '{{ gitea_project_display }}'
      spec: {}

- name: Deploy resources for Gitea Operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ resource.namespace|default(omit) }}'
    definition: '{{ lookup("url", resource.url, split_lines=False)|from_yaml|regex_replace("REPLACE_ME", gitea_project_name) }}'
  loop:
    - name: crd
      url: https://raw.githubusercontent.com/{{ github_project }}/gitea-operator/master/deploy/crds/gpte_v1alpha1_gitea_crd.yaml
    - name: cluster_role
      url: https://raw.githubusercontent.com/{{ github_project }}/gitea-operator/master/deploy/cluster_role.yaml
    - name: service_account
      url: https://raw.githubusercontent.com/{{ github_project }}/gitea-operator/master/deploy/service_account.yaml
      namespace: '{{ gitea_project_name }}'
    - name: cluster_role_binding
      url: https://raw.githubusercontent.com/{{ github_project }}/gitea-operator/master/deploy/cluster_role_binding.yaml
      namespace: '{{ gitea_project_name }}'
    - name: operator
      url: https://raw.githubusercontent.com/{{ github_project }}/gitea-operator/master/deploy/operator.yaml
      namespace: '{{ gitea_project_name }}'
  loop_control:
    loop_var: resource
    label: '{{ resource.name }}'

- name: Create Gitea from a CR
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ gitea_project_name }}'
    definition:
      apiVersion: gpte.opentlc.com/v1alpha1
      kind: Gitea
      metadata:
        name: gitea-server
      spec:
        postgresqlVolumeSize: 4Gi
        giteaVolumeSize: 4Gi
        giteaSsl: True
        giteaName: gitea
  register: gitea_deployment
  until: not gitea_deployment.failed
  retries: 5
  delay: 10
