---
- name: Gather all of the tokens for the created users
  set_fact:
    gitea_user_tokens: '{{ lookup("template", "tokens.yml.j2")|from_yaml }}'

- name: Wait for the Gitea to begin answering requests
  uri:
    url: https://gitea-server-{{ gitea_project_name }}.{{ cluster_router }}
    validate_certs: no
  register: gitea_available
  until: gitea_available.status != 503
  retries: 10
  delay: 10

- name: Make an API request to determine the User ID for each user
  uri:
    url: https://gitea-server-{{ gitea_project_name }}.{{ cluster_router }}/api/v1/user
    validate_certs: no
    body_format: json
    headers:
      Authorization: token {{ user.token }}
  register: gitea_user_ids
  loop: '{{ gitea_user_tokens }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'

- name: Gather all of the user IDs for the created users
  set_fact:
    gitea_user_tokens: '{{ lookup("template", "tokens_and_ids.yml.j2")|from_yaml }}'

- include_tasks: migrate_repo_task.yml
  loop: '{{ repos_to_load }}'
  loop_control:
    loop_var: repo
