---
workshop_spawner_project_name: devsecops
workshop_spawner_project_display: DevSecOps Common Resources

workshop_spawner_image: quay.io/redhatgov/workshop-spawner:latest
workshop_dashboard_image: quay.io/redhatgov/openshift-devsecops-labguides:{{ pipeline_style|default("tekton") }}

crw_project_name: devsecops

keycloak_url: "https://keycloak-{{ crw_project_name }}.apps.{{ cluster_name }}.{{ openshift_base_domain }}"
spawner_redirect_uri: "https://dashboard.apps.{{ cluster_name }}.{{ openshift_base_domain }}/hub/oauth_callback"
