<<<<<<< HEAD
- name: Ensure Mattermost Operator Namespace Exists
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Namespace
    name: "{{ mattermost_namespace }}"

- name: Subscribe to Mattermost Operator
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
=======
- name: Subscribe to Mattermost Operator
  community.kubernetes.k8s:
    state: present
>>>>>>> initial mattermost work
    definition: |-
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: mattermost-operator
        namespace: "{{ mattermost_namespace }}"
      spec:
        channel: "{{ mattermost_operator_channel }}"
        installPlanApproval: Automatic
        name: mattermost-operator
<<<<<<< HEAD
        source: redhatgov-operators
=======
        source: mattermost-operator
>>>>>>> initial mattermost work
        sourceNamespace: openshift-marketplace

- name: Create Mattermost 
  community.kubernetes.k8s:
    state: present
<<<<<<< HEAD
    kubeconfig: "{{ kubeconfig }}"
    resource_definition: "{{ lookup('template', 'mattermost-resource.yml.j2') }}"
=======
    resource_definition: "{{ lookup('template', 'mattermost-resource.yml') }}"
>>>>>>> initial mattermost work
