- name: Subscribe to Mattermost Operator
  community.kubernetes.k8s:
    state: present
    definition: |-
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: mattermost-operator
        namespace: "{{ mattermost_namespace }}"
      spec:
        channel: "{{ mattermost_operator_channel }}"
        installPlanApproval: Automatic
        name: mattermost-operator
        source: mattermost-operator
        sourceNamespace: openshift-marketplace

- name: Create Mattermost 
  community.kubernetes.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'mattermost-resource.yml') }}"
