---
- include_tasks: deploy_mattermost_operator.yml
  when: deploy_mattermost_operator | bool
<<<<<<< HEAD
<<<<<<< HEAD

- include_tasks: setup_keycloak_for_mattermost.yml
  when: authentication.keycloak.realmUrl is defined
=======
>>>>>>> initial mattermost work
=======

- include_tasks: setup_keycloak_for_mattermost.yml
  when: authentication.keycloak.realmUrl is defined
>>>>>>> a ton of changes to add keycloak integration to mattermost
