---
- name: Subscribe to Jenkins operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: jenkins-operator
        namespace: openshift-operators
      spec:
        channel: alpha
        installPlanApproval: Automatic
        name: jenkins-operator
        source: community-operators
        sourceNamespace: openshift-marketplace

- name: Allow Jenkins operator serviceaccount to create nonroot pods
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    merge_type: merge
    definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: nonroot
      users:
      - system:serviceaccount:openshift-operators:jenkins-operator

- name: Create a Jenkins instance for each user
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "jenkins_deployment.yml.j2")|from_yaml }}'
  register: jenkins_deployment
  until: not jenkins_deployment.failed
  retries: 5
  delay: 10
