- name: Ensure namespace exists
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ username_distribution_project_name }}'
        annotations:
          openshift.io/display-name: '{{ username_distribution_project_display }}'
      spec: {}

- name: Create Username Distribution Deployment
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ username_distribution_project_name }}'
    definition: "{{ lookup('template', 'username-distribution.yml.j2')|from_yaml }}"

- name: Wait for Username Distribution to finish being created
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: v1
    kind: Pod
    namespace: '{{ username_distribution_project_name }}'
    label_selectors:
      - app=username-distribution
  register: distro_pod
  until: distro_pod.resources|length > 0 and (distro_pod.resources|first).status.phase == "Running"
  retries: 10
  delay: 30
