---
- name: Download acme.sh
  git:
    repo: https://github.com/neilpang/acme.sh
    dest: '{{ _tmp_parent }}/acme.sh'

- name: Ensure certificate directory exists
  file:
    path: '{{ certificate_path }}'
    state: directory

- name: Get necessary certs
  shell: '{{ lookup("template", "quay_certs.sh.j2") }}'
  args:
    creates: '{{ certificate_path }}/quay-fullchain.pem'
  environment:
    AWS_ACCESS_KEY_ID: '{{ AWS_ACCESS_KEY_ID|default(ansible_env["AWS_ACCESS_KEY_ID"]) }}'
    AWS_SECRET_ACCESS_KEY: '{{ AWS_SECRET_ACCESS_KEY|default(ansible_env["AWS_SECRET_ACCESS_KEY"]) }}'
