---
- name: Download acme.sh
  git:
    repo: https://github.com/neilpang/acme.sh
    dest: '{{ tmp_dir }}/acme.sh'

- name: Ensure certificate directory exists
  file:
    path: '{{ certificate_path }}'
    state: directory

- name: Get necessary certs
  shell: |
    export KUBECONFIG='{{ kubeconfig }}'
    oc='{{ tmp_dir }}/oc'
    admin_user='{{ workshop_admin.username }}'
    admin_password='{{ workshop_admin.password }}'
    if [ $($oc whoami) != "$admin_user" ]; then
        $oc login --insecure-skip-tls-verify=true -u "$admin_user" -p "$admin_password" && echo changed || echo failed
    else
        echo ok
    fi

    quay_endpoint='quay.apps.{{ cluster_name }}.{{ openshift_base_domain }}'

    # Define our full path and reusable args
    acme='{{ tmp_dir }}/acme.sh/acme.sh'
    acme_args=(-d "$quay_endpoint" --dns dns_aws
        --cert-file '{{ certificate_path }}/quay-cert.pem'
        --key-file '{{ certificate_path }}/quay-key.pem'
        --ca-file '{{ certificate_path }}/quay-ca.pem'
        --fullchain-file '{{ certificate_path }}/quay-fullchain.pem'
    )
    # If there is a cert issued already
    if $acme --list | grep -qF "$quay_endpoint"; then
        # Try to install it
        if ! $acme --install-cert "${acme_args[@]}"; then
            # See about renewing it
            $acme --renew "${acme_args[@]}" --force || exit 1
        fi
    else
        # If no certs issued, request them
        $acme --issue "${acme_args[@]}" || exit 1
    fi
  args:
    creates: '{{ certificate_path }}/quay-fullchain.pem'
  environment:
    AWS_ACCESS_KEY_ID: '{{ AWS_ACCESS_KEY_ID|default(ansible_env["AWS_ACCESS_KEY_ID"]) }}'
    AWS_SECRET_ACCESS_KEY: '{{ AWS_SECRET_ACCESS_KEY|default(ansible_env["AWS_SECRET_ACCESS_KEY"]) }}'

- name: Subscribe to Quay Enterprise
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "quay.yml.j2")|from_yaml }}'

- name: Deploy Quay Enterprise via CR
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: redhatcop.redhat.io/v1alpha1
      kind: QuayEcosystem
      metadata:
        name: quayecosystem
        namespace: quay-enterprise
      spec:
        quay:
          imagePullSecretName: redhat-pull-secret
          superuserCredentialsSecretName: quay-superuser
          registryStorage:
            persistentVolumeSize: 10Gi
            persistentVolumeAccessModes:
              - ReadWriteOnce
          database:
            volumeSize: 10Gi
          routeHost: quay.apps.{{ cluster_name }}.{{ openshift_base_domain }}
          sslCertificatesSecretName: quay-tls-certs
        clair:
          enabled: true
          imagePullSecretName: redhat-pull-secret
  register: quay_deployment
  until: not quay_deployment.failed
  retries: 5
  delay: 10

- name: Wait for Quay route to be created by the Operator
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: route.openshift.io/v1
    kind: Route
    namespace: quay-enterprise
    name: quayecosystem-quay
  register: quay_route
  until: quay_route.resources|length > 0
  retries: 10
  delay: 30

- name: Wait for Quay route to begin answering requests
  uri:
    url: 'https://{{ quay_route|json_query("resources[0].spec.host") }}/'
    return_content: yes
    validate_certs: no
  register: quay_index
  until: '"DOCTYPE html" in quay_index.content'
  retries: 10
  delay: 30

- name: Add users to Quay instance
  shell: >-
    python3 {{ role_path }}/scripts/quay-user.py
    https://{{ quay_route|json_query("resources[0].spec.host") }}
    --login-username quay --login-password '{{ quay_password }}'
    {% for user in openshift_users %}
    {% if user.password|length >= 8 %}
    --username '{{ user.username }}' --password '{{ user.password }}'
    {% else %}
    --username '{{ user.username }}' --password password
    {% endif %}
    {% endfor %}
  register: quay_users
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0
