---
- name: Determine if we should do quay certs
  set_fact:
    do_quay_certs: (letsencrypt|bool and (AWS_ACCESS_KEY_ID is defined or ansible_env["AWS_ACCESS_KEY_ID"] is defined) and (AWS_ACCESS_KEY_ID|default("") != "" or ansible_env["AWS_ACCESS_KEY_ID"]|default("") != ""))|bool

- include_tasks: certificates.yml
  when: '{{ do_quay_certs }}'

- name: Subscribe to Quay Enterprise
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "quay.yml.j2")|from_yaml }}'

- name: Deploy Quay Enterprise via CR
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "quay_cr.yml.j2")|from_yaml }}'
  register: quay_deployment
  until: not quay_deployment.failed
  retries: 5
  delay: 10

- include_tasks: validate_route.yml
  when: quay_deployment.changed

- name: Wait for Quay route to begin answering requests
  uri:
    url: 'https://{{ quay_route }}/'
    return_content: yes
    validate_certs: no
  register: quay_index
  until: '"DOCTYPE html" in quay_index.content'
  retries: 10
  delay: 30

- name: Add users to Quay instance
  shell: >-
    devsecops-api quay add-user https://{{ quay_route }}
    --login-username quay --login-password '{{ quay_password }}'
    --usernames '{{ workshop_users|json_query("[].username")|join(",") }}'
    --passwords '{{ workshop_users|json_query("[].password")|join(",") }}'
  register: quay_users
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0

- name: Subscribe to container-security operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: container-security-operator
        namespace: openshift-operators
      spec:
        channel: quay-v3.3
        installPlanApproval: Automatic
        name: container-security-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

# Disabled for now until Quay API becomes more useful for automating Bridge
#   setup/prerequisites.
#
# - name: Install and configure Quay Bridge operator
#   include_tasks: quay_bridge.yml
