---
- name: Subscribe to quay-bridge operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: quay-bridge-operator
        namespace: openshift-operators
      spec:
        channel: quay-v3.3
        installPlanApproval: Automatic
        name: quay-bridge-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
