---
- name: Wait for Quay route to be created by the Operator
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: route.openshift.io/v1
    kind: Route
    namespace: quay-enterprise
    name: quayecosystem-quay
  register: quay_route_actual
  until: quay_route_actual.resources|length > 0
  retries: 10
  delay: 30

- name: Reapply Quay CR if necessary
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "quay_cr.yml.j2")|from_yaml }}'
  when: quay_route_actual|json_query("resources[0].spec.host") != quay_route

- name: Wait for Quay route to be fixed by the Operator
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: route.openshift.io/v1
    kind: Route
    namespace: quay-enterprise
    name: quayecosystem-quay
  register: quay_route_actual
  until: quay_route_actual|json_query("resources[0].spec.host") == quay_route
  retries: 10
  delay: 30
