---
- name: Add users to Quay instance
  shell: >-
    devsecops-api quay add-user https://{{ quay_route }}
    --login-username quay --login-password '{{ quay_password }}'
    --usernames '{{ workshop_users|json_query("[].username")|join(",") }}'
    --passwords '{{ workshop_users|json_query("[].password")|join(",") }}'
  register: quay_users
  # https://github.com/ansible/ansible/issues/27299
  # to_json|from_json| is a terrible hack but here we are
  changed_when: quay_users.stdout_lines|to_json|from_json|json_query("[?ends_with(@, ` added`)]")|length > 0



# Disabled for now until Quay API becomes more useful for automating Bridge
#   setup/prerequisites.
#
# - name: Install and configure Quay Bridge operator
#   include_tasks: quay_bridge.yml
