---
- name: Check if RWX storage is being provided by OCS
  fail:
    msg: |
      Unable to deploy 3scale without RWX storage provided by OCS or AWS S3.
      If you want to use S3, ensure your credentials are either in the
      environment or passed as extra_vars.

      Additionally, supply the variable `rwx_backing_s3_bucket` with the name
      of an S3 bucket to use that the credentials can already access. It will
      not be created automatically.
  when:
    - not (deploy_ocs|default(true))
    - rwx_backing_s3_bucket is not defined

- name: Subscribe to 3scale-operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "3scale.yml.j2")|from_yaml }}'

- name: Deploy 3scale API Manager via CR
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "api_manager.yml.j2")|from_yaml }}'
  register: api_manager_deployment
  until: not api_manager_deployment.failed
  retries: 5
  delay: 10
