---
- name: Ensure that the cluster tmp directory exists
  file:
    path: '{{ tmp_dir }}'
    state: directory

- import_tasks: download.yml
- import_tasks: prep.yml
- import_tasks: install.yml

- include_tasks: letsencrypt.yml
  when:
    - letsencrypt
    - AWS_ACCESS_KEY_ID is defined or ansible_env["AWS_ACCESS_KEY_ID"] is defined
    - AWS_ACCESS_KEY_ID|default("") != "" or ansible_env["AWS_ACCESS_KEY_ID"]|default("") != ""

- include_tasks: byo_cert.yml
  when:
    - not letsencrypt
    - byo_cert_fullchain_path is defined
    - byo_cert_fullchain_path != ""
    - byo_cert_key_path is defined
    - byo_cert_key_path != ""
