---
- name: Generate an SSH key for use with the cluster
  openssh_keypair:
    path: '{{ key_pair_path }}'
    size: 4096
    mode: 0600
    comment: '{{ workshop_admin.username }}@{{ full_cluster_name }}'
  register: cluster_key

- name: Register the keypair with the SSH agent
  shell: |
    eval "$(ssh-agent)"
    if ! ssh-add -l | grep -qF '{{ workshop_admin.username }}@{{ full_cluster_name }}'; then
        ssh-add {{ key_pair_path }} &>/dev/null && echo changed || echo failed
    else
        if ! ssh-add -T {{ key_pair_path }}.pub; then
            ssh-add -d {{ key_pair_path }} &>/dev/null
            ssh-add {{ key_pair_path }} &>/dev/null && echo changed || echo failed
        else
            echo ok
        fi
    fi
  register: ssh_add
  changed_when: ssh_add.stdout_lines|last == 'changed'
  failed_when: ssh_add.stdout_lines|last == 'failed'

- name: Check for existing kubeconfig
  stat:
    path: '{{ kubeconfig }}'
  register: kubeconfig_file

- name: Template install-config
  template:
    src: install-config.yaml.j2
    dest: '{{ tmp_dir }}/install-config.yaml'
  when: not kubeconfig_file.stat.exists
