---
- name: Subscribe to openshift-pipelines-operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-pipelines-operator
        namespace: openshift-operators
      spec:
        channel: dev-preview
        installPlanApproval: Automatic
        name: openshift-pipelines-operator
        source: community-operators
        sourceNamespace: openshift-marketplace
        startingCSV: openshift-pipelines-operator.v0.10.7

# Note: OpenShift Pipelines will create its own Config CR at installation time.
