---
- name: Recover existing machinesets
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
  register: machinesets

- name: Adjust machineset instancetype
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: openshift-machine-api
    merge_type: merge
    definition: '{{ lookup("template", "machinesets.yml.j2")|from_yaml }}'

- name: Create MachineAutoscaler for each machineset
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: openshift-machine-api
    apply: yes
    definition: '{{ lookup("template", "machine_autoscaler.yml.j2")|from_yaml }}'

- name: Create ClusterAutoscaler
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: openshift-machine-api
    apply: yes
    definition: '{{ lookup("template", "cluster_autoscaler.yml.j2")|from_yaml }}'
