---
- name: Recover existing machinesets
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
  register: machinesets

- name: Adjust machineset instancetype
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: openshift-machine-api
    merge_type: merge
    definition: '{{ lookup("template", "machinesets.yml.j2")|from_yaml }}'

- name: Create MachineAutoscaler for each machineset
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: openshift-machine-api
    apply: yes
    definition: '{{ lookup("template", "machine_autoscaler.yml.j2")|from_yaml }}'

- name: Create ClusterAutoscaler
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: openshift-machine-api
    apply: yes
    definition:
      apiVersion: autoscaling.openshift.io/v1
      kind: ClusterAutoscaler
      metadata:
        name: default
      spec:
        podPriorityThreshhold: -10
        resourceLimits:
          maxNodesTotal: '{{ cluster_max_nodes_total|int }}'
          cores:
            min: '{{ cluster_min_cores|int }}'
            max: '{{ cluster_max_cores|int }}'
          memory:
            min: '{{ cluster_min_ram_gb|int }}'
            max: '{{ cluster_max_ram_gb|int }}'
        scaleDown:
          enabled: true
          delayAfterAdd: 10m
          delayAfterDelete: 5m
          delayAfterFailure: 30s
          unneededTime: 60s
