---
- name: Update console route to be shorter
  k8s:
    state: present
    kubeconfig: '{{ kubeconfig }}'
    merge_type: merge
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: console
        namespace: openshift-console
      spec:
        host: console.{{ cluster_router }}
