---
- name: Create/update htpasswd file for users
  shell: |
    cd {{ tmp_dir }}
    [ -f users.htpasswd ] || touch users.htpasswd
    if htpasswd -v -b users.htpasswd '{{ user.username }}' '{{ user.password }}' &>/dev/null; then
        echo ok
    else
        htpasswd -B -b users.htpasswd '{{ user.username }}' '{{ user.password }}' &>/dev/null && echo changed || echo failed
    fi
  register: htpasswd
  changed_when: '"changed" in htpasswd.stdout_lines'
  failed_when: '"failed" in htpasswd.stdout_lines'
  loop: '{{ openshift_users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'

- name: Create/update the htpasswd secret
  k8s:
    state: present
    kubeconfig: '{{ tmp_dir }}/auth/kubeconfig'
    namespace: openshift-config
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        labels:
          type: htpasswd
        name: htpass-secret
      type: Opaque
      stringData:
        htpasswd: '{{ lookup("file", tmp_dir + "/users.htpasswd") }}'

- name: Create/update OAuth CR
  k8s:
    state: present
    kubeconfig: '{{ tmp_dir }}/auth/kubeconfig'
    apply: yes
    definition:
      apiVersion: v1
      kind: OAuth
      metadata:
        name: cluster
        labels:
          type: htpasswd
      spec:
        identityProviders:
        - name: htpasswd
          mappingMethod: claim
          type: HTPasswd
          htpasswd:
            fileData:
              name: htpass-secret
