---
- include_tasks: create_users.yml
  when: create_users
- include_tasks: letsencrypt.yml
  when: letsencrypt
- include_tasks: autoscale.yml
  when: autoscale
- include_tasks: console.yml
  when: adjust_console
