---
## Create Realm and Configure Openshift IDP

- name: Create Realm
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhsso-ocp-realm.yml.j2")|from_yaml }}'

- name: Create OCP SSO Client
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhsso-ocp-client.yml.j2")|from_yaml }}'

- name: Create RH-SSO IdP in OpenShift
  k8s_json_patch:
    kubeconfig: '{{ kubeconfig }}'
    api_version: config.openshift.io/v1
    kind: OAuth
    name: cluster
    patch:
      - op: add
        path: /spec/identityProviders/[?name='{{ item.name }}']
        value: '{{ item }}'
  loop:
    - name: rhsso-idp
      challenge: true
      login: true
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: "openshift"
        clientSecret:
          name: keycloak-client-secret-openshift
        extraScopes:
        - email
        - profile
        extraAuthorizeParameters:
          include_granted_scopes: "true"
        claims:
          preferredUsername:
          - preferred_username
          - email
          name:
          - nickname
          - given_name
          - name
          email:
          - custom_email_claim
          - email
        issuer: https://{{ rhsso_app_name }}-{{ rhsso_project_name }}.apps.{{ subdomain }}/auth/realms/{{ rhsso_realm_name }}

