---
- name: Create PostgreSQL Deployment
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhsso-postgresql.yml.j2")|from_yaml }}'

- name: Create RH-SSO Deployment
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhsso-deployment.yml.j2")|from_yaml }}'

