---
## Create Realm and Configure Openshift IDP

- name: Create Realm
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhsso-ocp-realm.yml.j2")|from_yaml }}'

- name: Create OCP SSO Client
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhsso-ocp-client.yml.j2")|from_yaml }}'

- name: Create RH-SSO IdP in OpenShift
  k8s_json_patch:
    kubeconfig: '{{ kubeconfig }}'
    api_version: config.openshift.io/v1
    kind: OAuth
    name: cluster
    patch:
      - op: add
        path: /spec/identityProviders/[?name='{{ item.name }}']
        value: '{{ item }}'
  loop: '{{ lookup("template", "rhsso-ocp-idp.yml.j2")|from_yaml }}'


