---
- hosts: localhost
  vars_files:
    - ../vars/provision.yml

  pre_tasks:
    - name: Set AWS_ACCESS_KEY_ID
      block:
      - pause:
          prompt: Enter your AWS Administrator account Access Key ID
        register: AWS_ACCESS_KEY_ID_tmp
      - set_fact:
          AWS_ACCESS_KEY_ID: '{{ AWS_ACCESS_KEY_ID_tmp.user_input }}'
      when: ('AWS_ACCESS_KEY_ID' not in ansible_env.keys())

    - name: Set AWS_SECRET_ACCESS_KEY
      block:
      - pause:
          prompt: Enter your AWS Administrator account Access Key Secret
        register: AWS_SECRET_ACCESS_KEY_tmp
      - set_fact:
          AWS_SECRET_ACCESS_KEY: '{{ AWS_SECRET_ACCESS_KEY_tmp.user_input }}'
      when: ('AWS_SECRET_ACCESS_KEY' not in ansible_env.keys())

  tasks:
    - include_role: openshift-installer
      when: install_openshift|default(true)

    # Individual adjustment tasks have their own toggles
    - include_role: cluster-adjuster
