---
- hosts: localhost
  pre_tasks:
    - name: Look for default defined common variables
      include_vars: ../vars/common.yml
      when: common_included is not defined or not common_included

    - fail:
        msg: Unable to continue without common variables set
      when: common_included is not defined or not common_included

    - name: Look for default defined rhedsord variables
      include_vars: ../vars/rhedsord.yml
      when: rhedsord_included is not defined or not rhedsord_included

    - fail:
        msg: Unable to continue without rhedsord variables set
      when: rhedsord_included is not defined or not rhedsord_included

  roles:
    - role: rhedsord
