---
- name: Create bookinfo Project
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      - apiVersion: project.openshift.io/v1
        kind: Project
        metadata:
          name: bookinfo
          labels:
            name: bookinfo
          annotations:
            openshift.io/display-name: 'BookInfo Service Mesh Application'

- name: Add bookinfo to ServiceMeshMemberRoll
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      - apiVersion: maistra.io/v1
        kind: ServiceMeshMemberRoll
        metadata:
          name: default
          namespace: istio-system
        spec:
          members:
          - bookinfo

- name: Wait for bookinfo to show as configured
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    namespace: istio-system
    kind: ServiceMeshMemberRoll
    name: default
  register: smm_roll
  until:
    - (smm_roll.resources|first).status.configuredMembers is defined
    - '"bookinfo" in (smm_roll.resources|first).status.configuredMembers'
  retries: 10
  delay: 30

- name: Create bookinfo application
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    namespace: bookinfo
    definition: '{{ lookup("url", bookinfo.url, split_lines=False) }}'
  loop:
    - name: application
      url: '{{ maistra_sample_url }}/bookinfo/platform/kube/bookinfo.yaml'
    - name: ingress gateway
      url: '{{ maistra_sample_url }}/bookinfo/networking/bookinfo-gateway.yaml'
    - name: mTLS destination rules
      url: '{{ maistra_sample_url }}/bookinfo/networking/destination-rule-all-mtls.yaml'
  loop_control:
    loop_var: bookinfo
    label: '{{ bookinfo.name }}'
